In [4]:
import pandas as pd
pd.set_option('max_columns', 200)
import geopandas as gpd

data = '../Permit_Data/'

### Building Permits Data Cleaning
Get the ADU related building permits and only keep the latest record

In [5]:
ADU_permits = pd.read_csv(data + 'Building_Permits_LA_ADU_filter.csv')

In [6]:
ADU_permits.shape

(8528, 54)

In [45]:
ADU_permits.head()

,Assessor Book,Assessor Page,Assessor Parcel,Tract,Block,Lot,Reference # (Old Permit #),PCIS Permit #,Status,Status Date,Permit Type,Permit Sub-Type,Permit Category,Project Number,Event Code,Initiating Office,Issue Date,Address Start,Address Fraction Start,Address End,Address Fraction End,Street Direction,Street Name,Street Suffix,Suffix Direction,Unit Range Start,Unit Range End,Zip Code,Work Description,Valuation,Floor Area-L.A. Zoning Code Definition,# of Residential Dwelling Units,# of Stories,Contractor's Business Name,Contractor Address,Contractor City,Contractor State,License Type,License #,Principal First Name,Principal Middle Name,Principal Last Name,License Expiration Date,Applicant First Name,Applicant Last Name,Applicant Business Name,Applicant Address 1,Applicant Address 2,Applicant Address 3,Zone,Occupancy,Floor Area-L.A. Building Code Definition,Census Tract,Latitude/Longitude
0,2669,19,7,TR 17820,NaN,219,17VN39070,17014-20000-00646,Issued,04/18/2017 12:00:00 AM,Bldg-Addition,1 or 2 Family Dwelling,Plan Check,NaN,NaN,VAN NUYS,04/18/2017,10015,NaN,10017,NaN,N,GAYNOR,AVE,NaN,NaN,NaN,91343.0,"NEW 36'-4"" X 14'-8"" ADDITION OF ACCESSORY DWEL...",52000.0,555.0,1.0,1.0,OWNER-BUILDER,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,HARRY,YASHAREL,NaN,4524 WHITE OAK PLACE,NaN,"ENCINO, CA",RS-1,NaN,555.00,1098.00,"(34.25247, -118.4809)"
1,2334,15,77,TR 11466,NaN,44,18VN,18043-20000-00504,Issued,01/29/2018 12:00:00 AM,Fire Sprinkler,1 or 2 Family Dwelling,Plan Check,NaN,NaN,VAN NUYS,01/29/2018,6012,NaN,6012,NaN,N,SIMPSON,AVE,NaN,NaN,NaN,91606.0,INSTALL FIRE SPRINKLER SYSTEM IN NEW ACCESSORY...,140000.0,NaN,NaN,NaN,GOLDEN STATE FIRE PROTECTION SYSTEM,17216 SATICOY STREET,VAN NUYS,CA,C16,848635,SAHAK,NaN,POGHOSYAN,10/31/2018,NaN,NaN,NaN,NaN,NaN,NaN,R1-1,NaN,0.00,1239.01,"(34.17995, -118.38873)"
2,6053,15,34,MONETA AVENUE HOME TRACT,C,22,19SL68396,19010-20000-04228,Issued,11/25/2019 12:00:00 AM,Bldg-New,1 or 2 Family Dwelling,Plan Check,NaN,NaN,VAN NUYS,11/25/2019,143,NaN,143,NaN,W,99TH,ST,NaN,NaN,NaN,90003.0,PROPOED NEW DETACHED ACCESSORY DWELLING UNIT P...,104000.0,1029.0,NaN,1.0,OWNER-BUILDER,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,HECTOR,PALAPA,NaN,1168 SAN GABRIEL BL,NaN,"ROSEMEAD, CA",R2-1,NaN,1029.00,2405.00,NaN
3,4264,4,29,P M 999,NaN,B,17WL83045,17016-10000-07558,Issued,08/25/2017 12:00:00 AM,Bldg-Alter/Repair,1 or 2 Family Dwelling,Plan Check,NaN,NaN,METRO,08/25/2017,13000,NaN,13000,NaN,W,BRENTWOOD,TER,NaN,NaN,NaN,90049.0,Converting Garage/Recreation Room to a Accesso...,293584.0,1901.0,NaN,2.0,C A A GENERAL CONTRACTOR,5901 COLFAX AVE,NORTH HOLLYWOOD,CA,B,696570,CESAR,AUGUSTO,ANDRINO,09/30/2018,JOSE,GONZALEZ,NaN,6210 WILSHIRE BLVD,NaN,"LOS ANGELES, CALIFORNIA",RE11-1,NaN,43.75,2643.02,"(34.04678, -118.48871)"
4,2656,6,22,TR 11395,NaN,16,17VN43450,17010-20000-00423,CofO Issued,03/02/2018 12:00:00 AM,Bldg-New,1 or 2 Family Dwelling,Plan Check,NaN,NaN,VAN NUYS,06/15/2017,9731,NaN,9731,NaN,N,BURNET,AVE,NaN,NaN,NaN,91343.0,"PROPOSED 30'-2"" X 55'-11"" ACCESSORY DWELLING U...",150000.0,1200.0,1.0,1.0,OWNER-BUILDER,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,GARY,AKOPIAN,NaN,3786 LA CRESCENTA,#201,"GLENDALE,CA",RA-1,NaN,1400.00,1171.02,NaN

In [17]:
# ADU_permits.columns

In [16]:
# ADU_permits.dtypes

In [15]:
# ADU_permits.isnull().sum()

In [77]:
ADU_build_permits = ADU_permits[ADU_permits['Permit Type'].isin(['Bldg-Addition', 'Bldg-New',
                                                                 'Bldg-Alter/Repair', 'Nonbldg-New'])]

In [78]:
ADU_permits_clean = ADU_build_permits[['Assessor Book', 'Assessor Page', 'Assessor Parcel', 
                                       'Work Description', 'Issue Date',
                                       'Valuation', 'Floor Area-L.A. Zoning Code Definition',
                                       '# of Residential Dwelling Units', '# of Stories', 'Zone']].copy()

In [79]:
ADU_permits_clean['Assessor Book'] = ADU_permits_clean['Assessor Book'].apply(lambda x: '{0:0>4}'.format(x))
ADU_permits_clean['Assessor Page'] = ADU_permits_clean['Assessor Page'].apply(lambda x: '{0:0>3}'.format(x))
ADU_permits_clean['Assessor Parcel'] = ADU_permits_clean['Assessor Parcel'].apply(lambda x: '{0:0>3}'.format(x))

In [80]:
ADU_permits_clean['APN_number'] = ADU_permits_clean['Assessor Book'].astype(str) + \
                                  ADU_permits_clean['Assessor Page'].astype(str) + \
                                  ADU_permits_clean['Assessor Parcel'].astype(str)

In [81]:
ADU_permits_clean = ADU_permits_clean.drop(['Assessor Book','Assessor Page','Assessor Parcel'], axis = 1)

In [82]:
ADU_permits_clean.dtypes

Work Description                           object
Issue Date                                 object
Valuation                                 float64
Floor Area-L.A. Zoning Code Definition    float64
# of Residential Dwelling Units           float64
# of Stories                              float64
Zone                                       object
APN_number                                 object
dtype: object

In [83]:
ADU_permits_clean['Issue Date'] =  pd.to_datetime(ADU_permits_clean['Issue Date'], format='%m/%d/%Y')

In [84]:
ADU_permits_clean.shape

(8076, 8)

In [85]:
ADU_permits_clean.head(10)

,Work Description,Issue Date,Valuation,Floor Area-L.A. Zoning Code Definition,# of Residential Dwelling Units,# of Stories,Zone,APN_number
0,"NEW 36'-4"" X 14'-8"" ADDITION OF ACCESSORY DWEL...",2017-04-18,52000.0,555.0,1.0,1.0,RS-1,2669019007
2,PROPOED NEW DETACHED ACCESSORY DWELLING UNIT P...,2019-11-25,104000.0,1029.0,NaN,1.0,R2-1,6053015034
3,Converting Garage/Recreation Room to a Accesso...,2017-08-25,293584.0,1901.0,NaN,2.0,RE11-1,4264004029
4,"PROPOSED 30'-2"" X 55'-11"" ACCESSORY DWELLING U...",2017-06-15,150000.0,1200.0,1.0,1.0,RA-1,2656006022
5,CONVERT (E) 1-STORY DETACHED IRR. GARAGE TO (N...,2017-04-03,45000.0,577.0,1.0,1.0,RA-1,2163003002
6,CONVERT EXISTING REC ROOM TO ACCESSORY DWELLIN...,2017-04-20,10000.0,391.0,1.0,2.0,R1-1,4255012022
7,CONVERT (E) RECREATION ROOM INTO AN ACCESSORY...,2020-02-10,12500.0,643.0,NaN,1.0,R1-1,7349026031
8,SUPPLEMENTAL TO PERMIT #18016-10000-23017 TO R...,2018-08-17,5000.0,NaN,NaN,NaN,R1-1,2112001029
10,Convert an existing office to ADU per AB 2299 ...,2017-04-20,12000.0,0.0,1.0,NaN,RE9-1,5556027019
11,"CONVERT THE (E) 20'4"" x 21'2"" GARAGE TO A NE...",2017-05-02,45000.0,520.0,1.0,0.0,R1-1-RIO,2130029005

In [96]:
latest_permit = ADU_permits_clean.sort_values('Issue Date').groupby('APN_number').tail(1)

In [164]:
latest_permit.shape

(7931, 8)

In [99]:
# ADU_permits_clean.APN_number.nunique() ==  ADU_permits_clean.shape[0]

In [97]:
latest_permit.APN_number.nunique() ==  latest_permit.shape[0]

True

In [12]:
# for permit_type in ADU_permits['Permit Type'].unique().tolist():
#     print(permit_type)
#     print(ADU_permits[ADU_permits['Permit Type']==permit_type]['Work Description'].head(2))

### Assessor Data

In [143]:
Assessor_parcels = pd.read_csv(data + 'Assessor_Parcels_Data_-_2019.csv')

/Users/xiaow/anaconda3/envs/musa-620/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (19,28,29,30,31,37,41,42,44) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [196]:
Assessor_parcels.head()

,ZIPcode,TaxRateArea_CITY,AIN,RollYear,TaxRateArea,AssessorID,PropertyLocation,PropertyType,PropertyUseCode,GeneralUseType,SpecificUseType,SpecificUseDetail1,SpecificUseDetail2,totBuildingDataLines,YearBuilt,EffectiveYearBuilt,SQFTmain,Bedrooms,Bathrooms,Units,RecordingDate,LandValue,LandBaseYear,ImprovementValue,ImpBaseYear,TotalLandImpValue,HomeownersExemption,RealEstateExemption,FixtureValue,FixtureExemption,PersonalPropertyValue,PersonalPropertyExemption,isTaxableParcel?,TotalValue,TotalExemption,netTaxableValue,SpecialParcelClassification,AdministrativeRegion,Cluster,ParcelBoundaryDescription,HouseNo,HouseFraction,StreetDirection,StreetName,UnitNo,City,ZIPcode5,rowID,CENTER_LAT,CENTER_LON,Location 1
0,91789-4036,DIAMOND BAR,8765017031,2019,10173,8765-017-031,20924 QUAIL RUN DR DIAMOND BAR CA 91789,SFR,0100,Residential,Single Family Residence,NaN,NaN,1,1986,1988,"1,901",3,3,1,19870721,"114,240.00",1986,"195,090.00",1986,"309,330.00","7,000.00",0.00,0,0,0.00,0.00,Y,"309,330.00","7,000.00","302,330.00",NaN,6,6159,TR=43162 LOT 48,20924,NaN,NaN,QUAIL RUN DR,NaN,DIAMOND BAR CA,91789.0,20198765017031,33.982467,-117.848366,"(33.98246687, -117.84836647)"
1,91789-4060,DIAMOND BAR,8765020011,2019,11950,8765-020-011,20923 E CANYON RIDGE LN DIAMOND BAR CA 91789,SFR,0100,Residential,Single Family Residence,NaN,NaN,1,1987,1988,"2,171",3,3,1,20080326,"102,938.00",1988,"222,988.00",1988,"325,926.00","7,000.00",0.00,0,0,0.00,0.00,Y,"325,926.00","7,000.00","318,926.00",NaN,6,6159,TR=43760 LOT 119,20923,NaN,E,CANYON RIDGE LN,NaN,DIAMOND BAR CA,91789.0,20198765020011,33.976384,-117.849724,"(33.97638402, -117.84972393)"
2,91789-4085,DIAMOND BAR,8765021098,2019,10328,8765-021-098,"20783 E CREST LN, #D WALNUT CA 91789",CND,010C,Residential,Single Family Residence,NaN,Condominium,1,1988,1988,912,2,2,1,20160930,"126,928.00",2017,"312,120.00",2017,"439,048.00",0.00,0.00,0,0,0.00,0.00,Y,"439,048.00",0.00,"439,048.00",NaN,6,6494,TR=43718 LOT 3 CONDOMINIUM UNIT 8,20783,NaN,E,CREST LN,#D,WALNUT CA,91789.0,20198765021098,33.979641,-117.853396,"(33.97964088, -117.85339604)"
3,91789-4000,DIAMOND BAR,8765022038,2019,10190,8765-022-038,20740 E RIM LN DIAMOND BAR CA 91789,SFR,0100,Residential,Single Family Residence,NaN,NaN,1,1987,1988,"2,747",4,3,1,19971010,"134,828.00",1998,"345,875.00",1998,"480,703.00",0.00,0.00,0,0,0.00,0.00,Y,"480,703.00",0.00,"480,703.00",NaN,6,6159,TR=44824 LOT 0038,20740,NaN,E,RIM LN,NaN,DIAMOND BAR CA,91789.0,20198765022038,33.981122,-117.853957,"(33.98112249, -117.85395656)"
4,91765,DIAMOND BAR,8765023039,2019,10067,8765-023-039,20620 PEACEFUL WOODS DR DIAMOND BAR CA 91765,CND,01DC,Residential,Single Family Residence,Detached,Condominium,1,2019,2019,"3,467",5,6,1,20151023,"603,041.00",2016,"475,800.00",2019,"1,078,841.00",0.00,0.00,0,0,0.00,0.00,Y,"1,078,841.00",0.00,"1,078,841.00",NaN,6,6159,TR=63623 POR LOT 8 PH 10 CONDO UNIT 29 (AIRSPA...,20620,NaN,NaN,PEACEFUL WOODS DR,NaN,DIAMOND BAR CA,91765.0,20198765023039,33.988432,-117.853275,"(33.988432, -117.85327457)"

In [198]:
Assessor_parcels.RollYear.nunique()

1

In [148]:
Assessor_parcels_clean = Assessor_parcels[['AIN', 'GeneralUseType', 'SpecificUseType', 'RecordingDate',
                                           'Bedrooms', 'Bathrooms', 'Units', 'TotalValue']].copy()
Assessor_parcels_clean['RecordingDate'] = pd.to_datetime(Assessor_parcels_clean['RecordingDate'], format='%Y%m%d', errors='coerce')

ADU_permits_clean['APN_number'] = ADU_permits_clean['APN_number'].astype(str)
Assessor_parcels_clean['AIN'] = Assessor_parcels_clean['AIN'].astype(str)

In [149]:
Assessor_parcels_clean.head()

,AIN,GeneralUseType,SpecificUseType,RecordingDate,Bedrooms,Bathrooms,Units,TotalValue
0,8765017031,Residential,Single Family Residence,1987-07-21,3,3,1,"309,330.00"
1,8765020011,Residential,Single Family Residence,2008-03-26,3,3,1,"325,926.00"
2,8765021098,Residential,Single Family Residence,2016-09-30,2,2,1,"439,048.00"
3,8765022038,Residential,Single Family Residence,1997-10-10,4,3,1,"480,703.00"
4,8765023039,Residential,Single Family Residence,2015-10-23,5,6,1,"1,078,841.00"

In [146]:
Assessor_parcels_clean.head()

,AIN,GeneralUseType,SpecificUseType,RecordingDate,Bedrooms,Bathrooms,Units,TotalValue
0,8765017031,Residential,Single Family Residence,19870721,3,3,1,"309,330.00"
1,8765020011,Residential,Single Family Residence,20080326,3,3,1,"325,926.00"
2,8765021098,Residential,Single Family Residence,20160930,2,2,1,"439,048.00"
3,8765022038,Residential,Single Family Residence,19971010,4,3,1,"480,703.00"
4,8765023039,Residential,Single Family Residence,20151023,5,6,1,"1,078,841.00"

In [172]:
joined_data = ADU_permits_clean.merge(Assessor_parcels_clean, how = 'left', 
                                      left_on = 'APN_number', right_on = 'AIN')

In [173]:
Assessor_parcels_clean[Assessor_parcels_clean['AIN'] == '2163003002']

,AIN,GeneralUseType,SpecificUseType,RecordingDate,Bedrooms,Bathrooms,Units,TotalValue
1275407,2163003002,Residential,Single Family Residence,2016-06-02,3,2,1,"230,441.00"

In [188]:
# pd.Assessor_parcels_clean['RecordingDate'].year
Assessor_parcels_clean['year'] = pd.DatetimeIndex(Assessor_parcels_clean['RecordingDate']).year

In [197]:
# a = Assessor_parcels_clean['year'].unique()
# a.sort()
# a

In [174]:
Assessor_parcels_clean.AIN.nunique()

2405570

In [175]:
Assessor_parcels_clean.shape

(2405570, 8)

In [176]:
joined_data.shape

(8076, 16)

In [177]:
joined_data.head()

,Work Description,Issue Date,Valuation,Floor Area-L.A. Zoning Code Definition,# of Residential Dwelling Units,# of Stories,Zone,APN_number,AIN,GeneralUseType,SpecificUseType,RecordingDate,Bedrooms,Bathrooms,Units,TotalValue
0,"NEW 36'-4"" X 14'-8"" ADDITION OF ACCESSORY DWEL...",2017-04-18,52000.0,555.0,1.0,1.0,RS-1,2669019007,2669019007,Residential,Single Family Residence,2017-01-06,3.0,2.0,1,"535,805.00"
1,PROPOED NEW DETACHED ACCESSORY DWELLING UNIT P...,2019-11-25,104000.0,1029.0,NaN,1.0,R2-1,6053015034,6053015034,Residential,Single Family Residence,2001-07-27,3.0,1.0,1,"124,380.00"
2,Converting Garage/Recreation Room to a Accesso...,2017-08-25,293584.0,1901.0,NaN,2.0,RE11-1,4264004029,4264004029,Residential,Single Family Residence,2016-03-11,3.0,3.0,1,"3,232,171.00"
3,"PROPOSED 30'-2"" X 55'-11"" ACCESSORY DWELLING U...",2017-06-15,150000.0,1200.0,1.0,1.0,RA-1,2656006022,2656006022,Residential,Single Family Residence,2016-04-19,5.0,4.0,2,"857,078.00"
4,CONVERT (E) 1-STORY DETACHED IRR. GARAGE TO (N...,2017-04-03,45000.0,577.0,1.0,1.0,RA-1,2163003002,2163003002,Residential,Single Family Residence,2016-06-02,3.0,2.0,1,"230,441.00"

In [178]:
joined_data.to_csv('joined_parcel_accessor.csv')

In [157]:
joined_data.AIN.nunique()

2405570

In [158]:
joined_data.shape

(2405747, 16)

In [199]:
# Assessor_parcels_clean[Assessor_parcels_clean['AIN']=='2669019007']

In [200]:
# ADU_permits_clean.dtypes

In [201]:
# Assessor_parcels_clean.dtypes

In [120]:
Assessor_parcels_clean.head(10)

,AIN,GeneralUseType,SpecificUseType,Bedrooms,Bathrooms,Units,TotalValue
0,8765017031,Residential,Single Family Residence,3,3,1,"309,330.00"
1,8765020011,Residential,Single Family Residence,3,3,1,"325,926.00"
2,8765021098,Residential,Single Family Residence,2,2,1,"439,048.00"
3,8765022038,Residential,Single Family Residence,4,3,1,"480,703.00"
4,8765023039,Residential,Single Family Residence,5,6,1,"1,078,841.00"
5,8765020001,Residential,Single Family Residence,3,3,1,"343,828.00"
6,8765023034,Residential,Single Family Residence,4,4,1,"950,800.00"
7,8765024072,Residential,Single Family Residence,4,4,1,"535,539.00"
8,8765019064,Residential,Single Family Residence,3,3,1,"499,851.00"
9,8765021080,Residential,Single Family Residence,3,2,1,"257,357.00"

In [111]:
latest_permit.APN_number

8242    2333003054
8306    2120031014
8365    5507006004
8335    2510002041
8503    2634037014
           ...
4817    2024026028
4799    2421003009
4820    4114033023
4809    5002002003
4780    2621029011
Name: APN_number, Length: 7931, dtype: object

In [114]:
test = Assessor_parcels[Assessor_parcels['AIN'] == '4114033023']

/Users/xiaow/anaconda3/envs/musa-620/lib/python3.6/site-packages/pandas/core/ops/array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)

In [115]:
test

Empty DataFrame
Columns: [ZIPcode, TaxRateArea_CITY, AIN, RollYear, TaxRateArea, AssessorID, PropertyLocation, PropertyType, PropertyUseCode, GeneralUseType, SpecificUseType, SpecificUseDetail1, SpecificUseDetail2, totBuildingDataLines, YearBuilt, EffectiveYearBuilt, SQFTmain, Bedrooms, Bathrooms, Units, RecordingDate, LandValue, LandBaseYear, ImprovementValue, ImpBaseYear, TotalLandImpValue, HomeownersExemption, RealEstateExemption, FixtureValue, FixtureExemption, PersonalPropertyValue, PersonalPropertyExemption, isTaxableParcel?, TotalValue, TotalExemption, netTaxableValue, SpecialParcelClassification, AdministrativeRegion, Cluster, ParcelBoundaryDescription, HouseNo, HouseFraction, StreetDirection, StreetName, UnitNo, City, ZIPcode5, rowID, CENTER_LAT, CENTER_LON, Location 1]
Index: []

In [21]:
Assessor_parcels.describe()

,AIN,RollYear,TaxRateArea,totBuildingDataLines,YearBuilt,EffectiveYearBuilt,Bedrooms,Bathrooms,RecordingDate,LandBaseYear,ImpBaseYear,Cluster,HouseNo,ZIPcode5,rowID,CENTER_LAT,CENTER_LON
count,2.405570e+06,2405570.0,2.405570e+06,2.405570e+06,2.405570e+06,2.405570e+06,2.405570e+06,2.405570e+06,2.405570e+06,2.405570e+06,2.405570e+06,2.405570e+06,2.405570e+06,2.281116e+06,2.405570e+06,2.404900e+06,2.404900e+06
mean,5.285674e+09,2019.0,4.290012e+03,9.893048e-01,1.778180e+03,1.783748e+03,3.152884e+00,2.393858e+00,2.007235e+07,1.991764e+03,1.991296e+03,8.577108e+03,6.963031e+03,9.105414e+04,2.019529e+13,3.409650e+01,-1.182426e+02
std,2.082185e+09,0.0,4.178285e+03,4.705598e-01,5.685042e+02,5.686621e+02,4.582225e+00,4.389576e+00,1.092447e+05,1.285040e+02,1.331297e+02,6.569947e+03,8.729858e+03,9.563696e+02,2.082185e+09,2.198418e-01,2.149533e-01
min,2.004001e+09,2019.0,4.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.800000e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.000000e+00,2.019200e+13,3.280448e+01,-1.189403e+02
25%,3.153093e+09,2019.0,6.700000e+01,1.000000e+00,1.938000e+03,1.947000e+03,2.000000e+00,1.000000e+00,2.003042e+07,1.988000e+03,1.989000e+03,3.182000e+03,8.680000e+02,9.026000e+04,2.019315e+13,3.395483e+01,-1.183936e+02
50%,5.354009e+09,2019.0,3.449000e+03,1.000000e+00,1.954000e+03,1.960000e+03,3.000000e+00,2.000000e+00,2.010122e+07,2.003000e+03,2.003000e+03,7.188000e+03,3.318000e+03,9.081500e+04,2.019535e+13,3.406741e+01,-1.182553e+02
75%,7.211009e+09,2019.0,7.500000e+03,1.000000e+00,1.975000e+03,1.979000e+03,4.000000e+00,3.000000e+00,2.015102e+07,2.013000e+03,2.013000e+03,1.116600e+04,1.053200e+04,9.150400e+04,2.019721e+13,3.417679e+01,-1.181059e+02
max,8.765025e+09,2019.0,1.684400e+04,5.000000e+00,2.019000e+03,2.019000e+03,4.950000e+02,4.950000e+02,2.019032e+07,2.019000e+03,2.204000e+03,3.089300e+04,9.259500e+04,9.960600e+04,2.019877e+13,3.482305e+01,-1.176523e+02

In [33]:
AddresstoAIN = pd.read_csv(data + 'AddresstoAIN.csv')

/Users/xiaow/anaconda3/envs/musa-620/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (37,41) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [35]:
AddresstoAIN.columns

Index(['ZIPcode', 'TaxRateArea_CITY', 'AIN', 'RollYear', 'TaxRateArea',
       'AssessorID', 'PropertyLocation', 'PropertyType', 'PropertyUseCode',
       'GeneralUseType', 'SpecificUseType', 'SpecificUseDetail1',
       'SpecificUseDetail2', 'totBuildingDataLines', 'YearBuilt',
       'EffectiveYearBuilt', 'SQFTmain', 'Bedrooms', 'Bathrooms', 'Units',
       'RecordingDate', 'LandValue', 'LandBaseYear', 'ImprovementValue',
       'ImpBaseYear', 'TotalLandImpValue', 'HomeownersExemption',
       'RealEstateExemption', 'FixtureValue', 'FixtureExemption',
       'PersonalPropertyValue', 'PersonalPropertyExemption',
       'isTaxableParcel?', 'TotalValue', 'TotalExemption', 'netTaxableValue',
       'SpecialParcelClassification', 'AdministrativeRegion', 'Cluster',
       'ParcelBoundaryDescription', 'HouseNo', 'HouseFraction',
       'StreetDirection', 'StreetName', 'UnitNo', 'City', 'ZIPcode5', 'rowID',
       'CENTER_LAT', 'CENTER_LON', 'Location 1'],
      dtype='object')

In [36]:
ADU_permits.columns

Index(['Assessor Book', 'Assessor Page', 'Assessor Parcel', 'Tract', 'Block',
       'Lot', 'Reference # (Old Permit #)', 'PCIS Permit #', 'Status',
       'Status Date', 'Permit Type', 'Permit Sub-Type', 'Permit Category',
       'Project Number', 'Event Code', 'Initiating Office', 'Issue Date',
       'Address Start', 'Address Fraction Start', 'Address End',
       'Address Fraction End', 'Street Direction', 'Street Name',
       'Street Suffix', 'Suffix Direction', 'Unit Range Start',
       'Unit Range End', 'Zip Code', 'Work Description', 'Valuation',
       'Floor Area-L.A. Zoning Code Definition',
       '# of Residential Dwelling Units', '# of Stories',
       'Contractor's Business Name', 'Contractor Address', 'Contractor City',
       'Contractor State', 'License Type', 'License #', 'Principal First Name',
       'Principal Middle Name', 'Principal Last Name',
       'License Expiration Date', 'Applicant First Name',
       'Applicant Last Name', 'Applicant Business Name', 'Applicant Address 1',
       'Applicant Address 2', 'Applicant Address 3', 'Zone', 'Occupancy',
       'Floor Area-L.A. Building Code Definition', 'Census Tract',
       'Latitude/Longitude'],
      dtype='object')

In [34]:
AddresstoAIN.head(10)

,ZIPcode,TaxRateArea_CITY,AIN,RollYear,TaxRateArea,AssessorID,PropertyLocation,PropertyType,PropertyUseCode,GeneralUseType,SpecificUseType,SpecificUseDetail1,SpecificUseDetail2,totBuildingDataLines,YearBuilt,EffectiveYearBuilt,SQFTmain,Bedrooms,Bathrooms,Units,RecordingDate,LandValue,LandBaseYear,ImprovementValue,ImpBaseYear,TotalLandImpValue,HomeownersExemption,RealEstateExemption,FixtureValue,FixtureExemption,PersonalPropertyValue,PersonalPropertyExemption,isTaxableParcel?,TotalValue,TotalExemption,netTaxableValue,SpecialParcelClassification,AdministrativeRegion,Cluster,ParcelBoundaryDescription,HouseNo,HouseFraction,StreetDirection,StreetName,UnitNo,City,ZIPcode5,rowID,CENTER_LAT,CENTER_LON,Location 1
0,91789-4036,DIAMOND BAR,8765017031,2019,10173,8765-017-031,20924 QUAIL RUN DR DIAMOND BAR CA 91789,SFR,0100,Residential,Single Family Residence,NaN,NaN,1,1986,1988,1901,3,3,1,19870721,114240.0,1986,195090.0,1986,309330.0,7000.0,0.0,0.0,0.0,0.0,0.0,Y,309330.0,7000.0,302330.0,NaN,6,6159,TR=43162 LOT 48,20924,NaN,NaN,QUAIL RUN DR,NaN,DIAMOND BAR CA,91789.0,20198765017031,33.982467,-117.848366,"(33.98246687, -117.84836647)"
1,91789-4060,DIAMOND BAR,8765020011,2019,11950,8765-020-011,20923 E CANYON RIDGE LN DIAMOND BAR CA 91789,SFR,0100,Residential,Single Family Residence,NaN,NaN,1,1987,1988,2171,3,3,1,20080326,102938.0,1988,222988.0,1988,325926.0,7000.0,0.0,0.0,0.0,0.0,0.0,Y,325926.0,7000.0,318926.0,NaN,6,6159,TR=43760 LOT 119,20923,NaN,E,CANYON RIDGE LN,NaN,DIAMOND BAR CA,91789.0,20198765020011,33.976384,-117.849724,"(33.97638402, -117.84972393)"
2,91789-4085,DIAMOND BAR,8765021098,2019,10328,8765-021-098,"20783 E CREST LN, #D WALNUT CA 91789",CND,010C,Residential,Single Family Residence,NaN,Condominium,1,1988,1988,912,2,2,1,20160930,126928.0,2017,312120.0,2017,439048.0,0.0,0.0,0.0,0.0,0.0,0.0,Y,439048.0,0.0,439048.0,NaN,6,6494,TR=43718 LOT 3 CONDOMINIUM UNIT 8,20783,NaN,E,CREST LN,#D,WALNUT CA,91789.0,20198765021098,33.979641,-117.853396,"(33.97964088, -117.85339604)"
3,91789-4000,DIAMOND BAR,8765022038,2019,10190,8765-022-038,20740 E RIM LN DIAMOND BAR CA 91789,SFR,0100,Residential,Single Family Residence,NaN,NaN,1,1987,1988,2747,4,3,1,19971010,134828.0,1998,345875.0,1998,480703.0,0.0,0.0,0.0,0.0,0.0,0.0,Y,480703.0,0.0,480703.0,NaN,6,6159,TR=44824 LOT 0038,20740,NaN,E,RIM LN,NaN,DIAMOND BAR CA,91789.0,20198765022038,33.981122,-117.853957,"(33.98112249, -117.85395656)"
4,91765,DIAMOND BAR,8765023039,2019,10067,8765-023-039,20620 PEACEFUL WOODS DR DIAMOND BAR CA 91765,CND,01DC,Residential,Single Family Residence,Detached,Condominium,1,2019,2019,3467,5,6,1,20151023,603041.0,2016,475800.0,2019,1078841.0,0.0,0.0,0.0,0.0,0.0,0.0,Y,1078841.0,0.0,1078841.0,NaN,6,6159,TR=63623 POR LOT 8 PH 10 CONDO UNIT 29 (AIRSPA...,20620,NaN,NaN,PEACEFUL WOODS DR,NaN,DIAMOND BAR CA,91765.0,20198765023039,33.988432,-117.853275,"(33.988432, -117.85327457)"
5,91789-4061,DIAMOND BAR,8765020001,2019,11950,8765-020-001,2700 S ROCKRIDGE LN DIAMOND BAR CA 91789,SFR,0101,Residential,Single Family Residence,NaN,Pool,1,1987,1987,1755,3,3,1,19910405,123532.0,1988,220296.0,1988,343828.0,7000.0,0.0,0.0,0.0,0.0,0.0,Y,343828.0,7000.0,336828.0,NaN,6,6159,TR=43760 LOT 109,2700,NaN,S,ROCKRIDGE LN,NaN,DIAMOND BAR CA,91789.0,20198765020001,33.977419,-117.849904,"(33.9774188, -117.84990401)"
6,91765,DIAMOND BAR,8765023034,2019,10067,8765-023-034,20619 PEACEFUL WOODS DR DIAMOND BAR CA 91765,CND,01DC,Residential,Single Family Residence,Detached,Condominium,1,2019,2019,3095,4,4,1,20151023,520200.0,2016,430600.0,2019,950800.0,0.0,0.0,0.0,0.0,0.0,0.0,Y,950800.0,0.0,950800.0,NaN,6,6159,TR=63623 POR LOT 8 PH 10 CONDO UNIT 24 (AIRSPA...,20619,NaN,NaN,PEACEFUL WOODS DR,NaN,DIAMOND BAR CA,91765.0,20198765023034,33.988432,-117.853275,"(33.988432, -117.85327457)"
7,91765,DIAMOND BAR,8765024072,2019,10067,8765-024-072,20672 SHEPHERD HILLS DR DIAMOND BAR CA 91765,CND,01DC,Residential,Single Family Residence,Detached,Condominium,1,2019,2019,3179,4,4,1,20151023,535539.0,2016,0.0,2016,535539.0,0.0,0.0,0.0,0.0,0.0,0.0,Y,535539.0,0.0,535539.0,NaN,6,6494,"TR=63623 POR LOTS 1,2 PH 11 CONDO UNIT 2 (AIRS...",20672,NaN,NaN,SHEPHERD HILLS DR,NaN,DIAMOND BAR CA,91765.0,20198765024072,33.988432,-117.853275,"(33.988432, -117.85327457)"
8,91789-4058,DIAMOND BAR,8765019064,2019,11950,8765-019-064,20841 E CANYON RIDGE LN DIAMOND BAR CA 91789,SFR,0100,Residential,Single Family Residence,NaN,NaN,1,1987,1987,1546,3,3,1,20051011,323541.0,2003,176310.0,2003,499851.0,0.0,0.0,0.0,0.0,0.0,0.0,Y,499851.0,0.0,499851.0,NaN,6,6159,TR=43760 LOT 102,20841,NaN,E,CANYON RIDGE LN,NaN,DIAMOND BAR CA,91789.0,20198765019064,33.977022,-117.851225,"(33.97702152, -117.85122451)"
9,91789-6200,DIAMOND BAR,8765021080,2019,10328,8765-021-080,"20711 E CREST LN, # B WALNUT CA 91789",CND,010C,Residential,Single Family Residence,NaN,Condominium,1,1987,1987,1217,3,2,1,19920902,58865.0,1989,198492.0,1989,257357.0,7000.0,0.0,0.0,0.0,0.0,0.0,Y,257357.0,7000.0,250357.0,NaN,6,6494,TR=43718 LOT 2 CONDOMINIUM UNIT 134,20711,NaN,E,CREST LN,# B,WALNUT CA,91789.0,20198765021080,33.978264,-117.854219,"(33.97826375, -117.85421924)"